Ant design setup
AccommoDateApp/accommodate-react pull request #11
Opened 2018-05-28 13:58 UTC by mshoaib91

antd css and scss plugins added

2018-05-28 14:08 UTC, michaelneu commented on package.json
> +    "scss-loader": "^0.0.1",
Why do we need `scss-loader`? The webpack config doesn't use this package, but rather the `sass-loader`.

The yarn lockfile should be affected as well.

2018-05-28 14:15 UTC, michaelneu commented on package.json
> +    "scss-loader": "^0.0.1",
I just checked and the package consists of an emtpy `package.json`. We should remove this dependency.

2018-05-29 20:45 UTC, tomasruizt approved these changes
Please make the changes requested. Afterwards, feel free to merge.

2018-05-29 20:45 UTC, tomasruizt commented on src/index.tsx
> +// css import
no need for this comment

2018-05-31 20:20 UTC, michaelneu requested changes
Tomas missed requesting changes, so I'll request them to prevent merging this into master.

2018-06-02 17:59 UTC, mshoaib91 commented
removed scss-loader

2018-06-02 18:02 UTC, tomasruizt approved these changes

2018-06-02 18:04 UTC, michaelneu approved these changes

2018-06-02 18:04 UTC, merged