Edit profile
AccommoDateApp/accommodate-react pull request #40
Opened 2018-06-29 17:18 UTC by aulonashabani

2018-06-29 17:23 UTC, michaelneu commented
@mshoaib91 should be reviewing this, to keep our review circle up.

2018-06-29 18:51 UTC, tomasruizt requested changes

2018-06-29 18:51 UTC, tomasruizt commented on src/actions/biographyActions.ts
> +      const updatedBio = await api.createAccommodation();
Lets keep a consistent naming as RealEstate

2018-06-29 18:51 UTC, tomasruizt commented on src/actions/imagesAction.ts
> +export const uploadAccommodationImage = (accommodationId: string, image: File) => {
Either they are all accommodations or all realEstates :D

2018-06-29 18:51 UTC, tomasruizt commented on src/api/client.ts
> +  public async uploadAccommodationImage(accommodationId: string, image: File) : Promise<any> {
here as well

2018-06-30 00:59 UTC, m5khan approved these changes
In Michi I trust :D

2018-06-30 00:59 UTC, mshoaib91 commented on src/actions/imagesAction.ts
> +    await fetchBiography()(dispatch);
Why are we fetching biography in image upload action 🤦‍♂️

2018-06-30 07:17 UTC, merged